name: Update Table of Contents

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x # Use the version of Python you need

    
    - name: Run Script
      run: python .github/scripts/update_readme.py

    - name: Update Repository
      if: github.event_name == 'push'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "username@users.noreply.github.com"
        git status
        git add README.md
        git commit -m "GitHub Actions: Update README to sort language sections alphabetically"
        git push
